### ISSUE TITLE
certs_*.json

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroID#23]
Maybe add some documentation on the format ZeroID uses? I looked through code and can't find any information about new `certs_*.json` in this repository.

**Comment by HelloZeroNet** [comment]
It's just an optimization to the site: 
As we are getting more users storing the old signatures are became problematic.
As a solution I moved older signs to optional files (certs_*) and keeping only the usernames and the first 6 letter of auth_address in users.json and users_archive.json.

The first 6 letter of auth_address is necessary, because if you have a clean install and you want to recover your certificate from ZeroID you don't know the username, so you have to find user by auth_address.

It's possible that in the future we will remove storing old certificates in the future. As it's possible from recover it from any site you have posted before.

So:
 - users.json: Latest usernames + certificates
 - users_archive.json: Older usernames + certificate for the one that has not been archived yet (it will be moved to cert_* files if it reached 6000 non-archived certificates). For archived users it hold the cert file number (eg.: @10) and the first 6 letter of auth_address.
 - certs_*.json: Older certificates in optional files
